### ISSUE TITLE
Zero by degree reasons

### ISSUE THREAD

**Issue by ammedmar** [Steenroder/steenroder#11]
As illustrated in the notebook *test*, our implementation is failing to give an empty sq^k-barcode in dimension d+k when d<k. Recall that if a is a cocycle of degree d then Sq^k(a)=0 if k > d.

**Comment by ammedmar** [comment]
More details: according to the docstrings:
``steenrod_matrix[d][j]`` is the result of computing the Steenrod square of ``coho_reps[d][j]``.
In particular, I would expect that the length of these two lists to be the same. This is not the case in the problematic situations for Sq^2 I have tested using the cp2 and RP4. In those cases there are bad infinite Sq^2-bars. These correspond to the ``coho_reps[d]``, and the associated ``steenrod_matrix[d]`` is empty instead of populated by empty lists one for each coho_rep.

**Comment by ulupo** [comment]
> steenrod_matrix[d][j] is the result of computing the Steenrod square of coho_reps[d][j]

This may be a typo in the docstrings.  I thought it actually should be

> steenrod_matrix[d][j] is the result of computing the Steenrod square of coho_reps[d - k][j]

If things were actually this way, would your tests make more sense?

**Comment by ammedmar** [comment]
Yes, that fixes it.

Another point. Studying `_steenrod_barcode_single_dim` I found the/a problem: The second loop `for ii in range(n, n + j):` is never entered since `j`, initialized as `0`, remains unchanged thru the whole process. Therefore, `alive` is never updated.

**Comment by ammedmar** [comment]
More details:
The condition that updates `j++` is `births_dim[j] == idx` where `idx` runs thru `idxs_prev_dim`. I think the reason we don't see the problem in the `k=1` case is because  `idxs_prev_dim` agrees with the cocycles in the domain of Sq^1.

**Comment by ulupo** [comment]
>  The condition that updates j++ is births_dim[j] == idx where idx runs thru idxs_prev_dim. I think the reason we don't see the problem in the k=1 case is because idxs_prev_dim agrees with the cocycles in the domain of Sq^1.

Thanks, I think I see the issue and this sounds like a convincing reason why we didn't see anything wrong with k=1.  I'll try a fix.

**Comment by ulupo** [comment]
Does replacing

>        if births_dim[j] == idx:

with

>        if births_dim[j] <= idx:

work?

**Comment by ulupo** [comment]
I've tried a fix in [the `fix_large_k` branch](https://github.com/Steenroder/steenroder/pull/12), could you please explore whether it fixes the newly revealed bug without changing the results for `k=1`?

**Comment by ammedmar** [comment]
Hi there, thanks for the work. Unfortunately, it does not fix the problem. The fix removed the weird deg 2 Sq^2-bar in the RP2 case, but there are equally weird Sq^2-bars in degree 3 and 4 in the CP2 case. I added the notebook *cp2* illustrating this to the `fix_large_k` branch. I also added the notebook *real_projective_spaces* to help making sure the changes don't mess Sq^1 up. If you want we can go over the code together.

**Comment by ulupo** [comment]
Thanks for checking!  Are the weird bars exactly the same as the ones you got in the `main` branch?  Or have we at least removed a few?

**Comment by ulupo** [comment]
I think I understand what has happened, am working on a fix!

**Comment by ulupo** [comment]
Fixed in #12.
